apiVersion: apps/v1
kind: Deployment
metadata:
  name: we-marketplace
  namespace: we-marketplace-prd
  labels:
    app: we-marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: we-marketplace
  template:
    metadata:
      labels:
        app: we-marketplace
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: we-marketplace
        image: ghcr.io/wedigitek/web-marketplace:rc
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "200m"
