apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: we-api-integrations-service-keyvault-env
  namespace: we-api-integrations-service-prd
spec:
  provider: azure
  secretObjects:
  - secretName: we-api-integrations-service-secrets-kv
    type: Opaque
    data:
    - objectName: we-api-integrations-service-logger
      key: LOGGER
    - objectName: we-api-integrations-service-loglevel
      key: LOGLEVEL
    - objectName: we-api-integrations-service-namespace
      key: NAMESPACE
    - objectName: we-api-integrations-service-servicedir
      key: SERVICEDIR
    - objectName: we-api-integrations-service-we-activity-logs-db-name
      key: WE_ACTIVITY_LOGS_DB_NAME
    - objectName: we-api-integrations-service-we-client-services-namespace
      key: WE_CLIENT_SERVICES_NAMESPACE
    - objectName: we-api-integrations-service-we-client-services-transporter
      key: WE_CLIENT_SERVICES_TRANSPORTER
    - objectName: we-api-integrations-service-we-integrations-daimler-order-apikey
      key: WE_INTEGRATIONS_DAIMLER_ORDER_APIKEY
    - objectName: we-api-integrations-service-we-integrations-daimler-order-security-key
      key: WE_INTEGRATIONS_DAIMLER_ORDER_SECURITY_KEY
    - objectName: we-api-integrations-service-we-integrations-daimler-order-url
      key: WE_INTEGRATIONS_DAIMLER_ORDER_URL
    - objectName: we-api-integrations-service-we-integrations-db-connection-string
      key: WE_INTEGRATIONS_DB_CONNECTION_STRING
    - objectName: we-api-integrations-service-we-integrations-node-env
      key: WE_INTEGRATIONS_NODE_ENV
    - objectName: we-api-integrations-service-we-integrations-wdt-db-connection-string
      key: WE_INTEGRATIONS_WDT_DB_CONNECTION_STRING
    - objectName: we-api-integrations-service-transporter
      key: TRANSPORTER
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: we-api-integrations-service-logger
          objectType: secret
        - |
          objectName: we-api-integrations-service-loglevel
          objectType: secret
        - |
          objectName: we-api-integrations-service-namespace
          objectType: secret
        - |
          objectName: we-api-integrations-service-servicedir
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-activity-logs-db-name
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-client-services-namespace
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-client-services-transporter
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-integrations-daimler-order-apikey
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-integrations-daimler-order-security-key
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-integrations-daimler-order-url
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-integrations-db-connection-string
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-integrations-node-env
          objectType: secret
        - |
          objectName: we-api-integrations-service-we-integrations-wdt-db-connection-string
          objectType: secret
        - |
          objectName: we-api-integrations-service-transporter
          objectType: secret
