apiVersion: v1
kind: Service
metadata:
  name: we-api-integrations-service
  namespace: we-api-integrations-service-prd
  labels:
    app: we-api-integrations-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: we-api-integrations-service
