apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: billing-prd
  labels:
    app: billing
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      volumes:
      - name: keyvault-env
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: billing-keyvault-env
      - name: sefaz-certificates
        persistentVolumeClaim:
          claimName: sefaz-certificates
      - name: cdn-invoices
        persistentVolumeClaim:
          claimName: cdn-invoices
      containers:
      - name: billing
        image: ghcr.io/wedigitek/we-services-billing:rc
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: billing-secrets-kv
        volumeMounts:
        - name: keyvault-env
          mountPath: /mnt/secrets-store
          readOnly: true
        - name: sefaz-certificates
          mountPath: /app/certificates
        - name: cdn-invoices
          mountPath: /app/invoices/xml
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "200m"

