apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing-prd

resources:
  - secretproviderclass-files.yaml
  - secretproviderclass-env.yaml
  - namespace.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      environment: production
      managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/billing
    newName: ghcr.io/wedigitek/we-services-billing
    newTag: rc
