apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing-prd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: billing
  environment: production
  managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/billing
    newTag: latest
