apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: billing-keyvault-env
  namespace: billing-prd
spec:
  provider: azure
  secretObjects:
  - secretName: billing-secrets-kv
    type: Opaque
    data:
    - objectName: billing-logger
      key: LOGGER
    - objectName: billing-loglevel
      key: LOGLEVEL
    - objectName: billing-we-billing-services-acube-base-url
      key: WE_BILLING_SERVICES_ACUBE_BASE_URL
    - objectName: billing-we-billing-services-acube-login-base-url
      key: WE_BILLING_SERVICES_ACUBE_LOGIN_BASE_URL
    - objectName: billing-we-billing-services-acube-login-email
      key: WE_BILLING_SERVICES_ACUBE_LOGIN_EMAIL
    - objectName: billing-we-billing-services-acube-login-password
      key: WE_BILLING_SERVICES_ACUBE_LOGIN_PASSWORD
    - objectName: billing-we-billing-services-acube-unavailability-window-timeout
      key: WE_BILLING_SERVICES_ACUBE_UNAVAILABILITY_WINDOW_TIMEOUT
    - objectName: billing-we-billing-services-at-base-url
      key: WE_BILLING_SERVICES_AT_BASE_URL
    - objectName: billing-we-billing-services-at-cert-passphrase
      key: WE_BILLING_SERVICES_AT_CERT_PASSPHRASE
    - objectName: billing-we-billing-services-at-cert-path
      key: WE_BILLING_SERVICES_AT_CERT_PATH
    - objectName: billing-we-billing-services-at-pub-key-path
      key: WE_BILLING_SERVICES_AT_PUB_KEY_PATH
    - objectName: billing-we-billing-services-db-connection-string
      key: WE_BILLING_SERVICES_DB_CONNECTION_STRING
    - objectName: billing-we-billing-services-encryption-secret
      key: WE_BILLING_SERVICES_ENCRYPTION_SECRET
    - objectName: billing-we-billing-services-logger-enabled
      key: WE_BILLING_SERVICES_LOGGER_ENABLED
    - objectName: billing-we-billing-services-logger-lvl
      key: WE_BILLING_SERVICES_LOGGER_LVL
    - objectName: billing-we-billing-services-namespace
      key: WE_BILLING_SERVICES_NAMESPACE
    - objectName: billing-we-billing-services-node-env
      key: WE_BILLING_SERVICES_NODE_ENV
    - objectName: billing-we-billing-services-paths-invoice-xml
      key: WE_BILLING_SERVICES_PATHS_INVOICE_XML
    - objectName: billing-we-billing-services-transporter
      key: WE_BILLING_SERVICES_TRANSPORTER
    - objectName: billing-we-billing-services-wdt-db-connection-string
      key: WE_BILLING_SERVICES_WDT_DB_CONNECTION_STRING
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: billing-logger
          objectType: secret
        - |
          objectName: billing-loglevel
          objectType: secret
        - |
          objectName: billing-we-billing-services-acube-base-url
          objectType: secret
        - |
          objectName: billing-we-billing-services-acube-login-base-url
          objectType: secret
        - |
          objectName: billing-we-billing-services-acube-login-email
          objectType: secret
        - |
          objectName: billing-we-billing-services-acube-login-password
          objectType: secret
        - |
          objectName: billing-we-billing-services-acube-unavailability-window-timeout
          objectType: secret
        - |
          objectName: billing-we-billing-services-at-base-url
          objectType: secret
        - |
          objectName: billing-we-billing-services-at-cert-passphrase
          objectType: secret
        - |
          objectName: billing-we-billing-services-at-cert-path
          objectType: secret
        - |
          objectName: billing-we-billing-services-at-pub-key-path
          objectType: secret
        - |
          objectName: billing-we-billing-services-db-connection-string
          objectType: secret
        - |
          objectName: billing-we-billing-services-encryption-secret
          objectType: secret
        - |
          objectName: billing-we-billing-services-logger-enabled
          objectType: secret
        - |
          objectName: billing-we-billing-services-logger-lvl
          objectType: secret
        - |
          objectName: billing-we-billing-services-namespace
          objectType: secret
        - |
          objectName: billing-we-billing-services-node-env
          objectType: secret
        - |
          objectName: billing-we-billing-services-paths-invoice-xml
          objectType: secret
        - |
          objectName: billing-we-billing-services-transporter
          objectType: secret
        - |
          objectName: billing-we-billing-services-wdt-db-connection-string
          objectType: secret
