apiVersion: apps/v1
kind: Deployment
metadata:
  name: we-admin
  namespace: we-admin-prd
  labels:
    app: we-admin
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: we-admin
  template:
    metadata:
      labels:
        app: we-admin
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      volumes:
      - name: keyvault-env
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: we-admin-keyvault-env
      containers:
      - name: we-admin
        image: ghcr.io/wedigitek/we-admin:rc
        imagePullPolicy: Always
        volumeMounts:
        - name: keyvault-env
          mountPath: /mnt/keyvault-env
          readOnly: true
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
