apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-devices
  namespace: service-devices
  labels:
    app: service-devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-devices
  template:
    metadata:
      labels:
        app: service-devices
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: service-devices
        image: ghcr.io/wedigitek/we-services-devices:main
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: WE_DEVICES_DB_CONNECTION_STRING
          value: mongodb://braveNewWorld:gogoPowerRangers!!@mrburns.azr.wdtsrv.com:27017/wedigitek
        - name: WE_DEVICES_SERVICES_NAMESPACE
          value: WE-API-SERVICES
        - name: WE_DEVICES_TRANSPORTER
          value: nats://nats.messaging.svc.cluster.local:4222
        - name: WE_DEVICES_MQTT_URL
          value: mqtts://broker-mqtt.broker-mqtt.svc.cluster.local:8884
        - name: WE_DEVICES_MQTT_USERNAME
          value: service-devices
        - name: WE_DEVICES_MQTT_PASSWORD_FILE
          value: /run/secrets/mqtt_password
        - name: WE_DEVICES_CA_CERT_PATH
          value: /run/secrets/ca.crt
        - name: WE_DEVICES_CA_KEY_PATH
          value: /run/secrets/ca.key
        - name: WE_DEVICES_IOT_MQTT_HOST
          value: mqtt.trywefood.dev
        - name: WE_DEVICES_IOT_MQTT_PORT
          value: "8883"
        - name: WE_DEVICES_WE_API_URL
          value: https://api.trywefood.dev
        - name: WE_DEVICES_NATS_PING_INTERVAL
          value: "30000"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        volumeMounts:
        - name: keyvault-files
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: keyvault-files
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: service-devices-keyvault-files
