apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-devices

resources:
  - namespace.yaml
  - secretproviderclass-files.yaml
  - deployment.yaml
  - deployment-mongo.yaml
  - service.yaml
  - service-mongo.yaml

labels:
  - pairs:
      environment: production
      managed-by: argocd
