apiVersion: v1
kind: Service
metadata:
  name: service-devices
  namespace: service-devices
  labels:
    app: service-devices
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: service-devices
