apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: surveys-keyvault-env
  namespace: surveys-prd
spec:
  provider: azure
  secretObjects:
  - secretName: surveys-secrets-kv
    type: Opaque
    data:
    - objectName: surveys-we-accepted-requests-origin-domains
      key: WE_ACCEPTED_REQUESTS_ORIGIN_DOMAINS
    - objectName: surveys-we-qa-services-transporter
      key: WE_QA_SERVICES_TRANSPORTER
    - objectName: surveys-we-surveys-services-address
      key: WE_SURVEYS_SERVICES_ADDRESS
    - objectName: surveys-we-surveys-services-db-connection-string
      key: WE_SURVEYS_SERVICES_DB_CONNECTION_STRING
    - objectName: surveys-we-surveys-services-logger-enabled
      key: WE_SURVEYS_SERVICES_LOGGER_ENABLED
    - objectName: surveys-we-surveys-services-logger-lvl
      key: WE_SURVEYS_SERVICES_LOGGER_LVL
    - objectName: surveys-we-surveys-services-namespace
      key: WE_SURVEYS_SERVICES_NAMESPACE
    - objectName: surveys-we-surveys-services-node-env
      key: WE_SURVEYS_SERVICES_NODE_ENV
    - objectName: surveys-we-surveys-services-port
      key: WE_SURVEYS_SERVICES_PORT
    - objectName: surveys-we-surveys-services-transporter
      key: WE_SURVEYS_SERVICES_TRANSPORTER
    - objectName: surveys-we-surveys-swagger-host
      key: WE_SURVEYS_SWAGGER_HOST
    - objectName: surveys-we-surveys-swagger-password
      key: WE_SURVEYS_SWAGGER_PASSWORD
    - objectName: surveys-we-surveys-swagger-scheme
      key: WE_SURVEYS_SWAGGER_SCHEME
    - objectName: surveys-we-surveys-swagger-username
      key: WE_SURVEYS_SWAGGER_USERNAME
    - objectName: surveys-we-surveys-wefood-apis-base-url
      key: WE_SURVEYS_WEFOOD_APIS_BASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: surveys-we-accepted-requests-origin-domains
          objectType: secret
        - |
          objectName: surveys-we-qa-services-transporter
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-address
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-db-connection-string
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-logger-enabled
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-logger-lvl
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-namespace
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-node-env
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-port
          objectType: secret
        - |
          objectName: surveys-we-surveys-services-transporter
          objectType: secret
        - |
          objectName: surveys-we-surveys-swagger-host
          objectType: secret
        - |
          objectName: surveys-we-surveys-swagger-password
          objectType: secret
        - |
          objectName: surveys-we-surveys-swagger-scheme
          objectType: secret
        - |
          objectName: surveys-we-surveys-swagger-username
          objectType: secret
        - |
          objectName: surveys-we-surveys-wefood-apis-base-url
          objectType: secret
