apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-logs-service
  namespace: activity-logs-service-prd
  labels:
    app: activity-logs-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: activity-logs-service
  template:
    metadata:
      labels:
        app: activity-logs-service
    spec:
      containers:
      - name: activity-logs-service
        image: acrwedigitekprd.azurecr.io/we-api-activity-logs-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - secretRef:
            name: activity-logs-service-secrets-kv
        volumeMounts:
        - name: keyvault-env
          mountPath: /mnt/secrets-store
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: keyvault-env
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: activity-logs-service-keyvault-env
