apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: activity-logs-service-prd

resources:
  - namespace.yaml
  - secretproviderclass-env.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      environment: production
      managed-by: argocd

