apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: we-loyalty-service-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wedigitek/wedigitek-k8s-gitops.git
    targetRevision: main
    path: applications/prd/we-loyalty-service
  destination:
    server: https://kubernetes.default.svc
    namespace: we-loyalty-service-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
