apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: we-loyalty-service-prd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: we-loyalty-service
  environment: production
  managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/we-loyalty-service
    newTag: latest
