apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: we-loyalty-service-keyvault-env
  namespace: we-loyalty-service-prd
spec:
  provider: azure
  secretObjects:
  - secretName: we-loyalty-service-secrets-kv
    type: Opaque
    data:
    - objectName: we-loyalty-service-logger
      key: LOGGER
    - objectName: we-loyalty-service-loglevel
      key: LOGLEVEL
    - objectName: we-loyalty-service-namespace
      key: NAMESPACE
    - objectName: we-loyalty-service-servicedir
      key: SERVICEDIR
    - objectName: we-loyalty-service-we-client-services-transporter
      key: WE_CLIENT_SERVICES_TRANSPORTER
    - objectName: we-loyalty-service-we-loyalty-db-connection-string
      key: WE_LOYALTY_DB_CONNECTION_STRING
    - objectName: we-loyalty-service-we-loyalty-db-name
      key: WE_LOYALTY_DB_NAME
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: we-loyalty-service-logger
          objectType: secret
        - |
          objectName: we-loyalty-service-loglevel
          objectType: secret
        - |
          objectName: we-loyalty-service-namespace
          objectType: secret
        - |
          objectName: we-loyalty-service-servicedir
          objectType: secret
        - |
          objectName: we-loyalty-service-we-client-services-transporter
          objectType: secret
        - |
          objectName: we-loyalty-service-we-loyalty-db-connection-string
          objectType: secret
        - |
          objectName: we-loyalty-service-we-loyalty-db-name
          objectType: secret
