apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveys-reports
  namespace: surveys-reports-prd
  labels:
    app: surveys-reports
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveys-reports
  template:
    metadata:
      labels:
        app: surveys-reports
    spec:
      containers:
      - name: surveys-reports
        image: ghcr.io/wedigitek/reports-surveys:rc
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: surveys-reports-secrets-kv
        volumeMounts:
        - name: keyvault-env
          mountPath: /mnt/secrets-store
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: keyvault-env
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: surveys-reports-keyvault-env
