apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: surveys-reports-prd

resources:
  - namespace.yaml
  - secretproviderclass-env.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      environment: production
      managed-by: argocd

images:
  - name: ghcr.io/wedigitek/reports-surveys
    newTag: rc
