apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-control
  namespace: access-control-prd
  labels:
    app: access-control
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: access-control
  template:
    metadata:
      labels:
        app: access-control
    spec:
      containers:
      - name: access-control
        image: ghcr.io/wedigitek/we-services-access-control:rc
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - secretRef:
            name: access-control-secrets-kv
        volumeMounts:
        - name: keyvault-env
          mountPath: /mnt/secrets-store
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: keyvault-env
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: access-control-keyvault-env
