apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: access-control-keyvault-env
  namespace: access-control-prd
spec:
  provider: azure
  secretObjects:
  - secretName: access-control-secrets-kv
    type: Opaque
    data:
    - objectName: access-control-node-env
      key: NODE_ENV
    - objectName: access-control-port
      key: PORT
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: access-control-node-env
          objectType: secret
        - |
          objectName: access-control-port
          objectType: secret
