apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: broker-mqtt-keyvault-files
  namespace: broker-mqtt
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: broker-mqtt-ca-crt
          objectType: secret
          objectAlias: ca.crt
        - |
          objectName: broker-mqtt-ca-key
          objectType: secret
          objectAlias: ca.key
        - |
          objectName: broker-mqtt-server-crt
          objectType: secret
          objectAlias: broker.crt
        - |
          objectName: broker-mqtt-server-key
          objectType: secret
          objectAlias: broker.key
        - |
          objectName: broker-mqtt-service-devices-password
          objectType: secret
          objectAlias: mqtt_password
        - |
          objectName: broker-mqtt-vmq-pwd
          objectType: secret
          objectAlias: vmq.passwd
        - |
          objectName: broker-mqtt-acl
          objectType: secret
          objectAlias: vmq.acl
