apiVersion: apps/v1
kind: Deployment
metadata:
  name: wefood-delivery-notifier
  namespace: wefood-delivery-notifier-prd
  labels:
    app: wefood-delivery-notifier
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wefood-delivery-notifier
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
      labels:
        app: wefood-delivery-notifier
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: wefood-delivery-notifier
        image: ghcr.io/wedigitek/wefood-delivery-notifier:main
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: wefood-delivery-notifier-secrets-kv
        env:
        - name: WE_API_DB_CONNECTION_STRING
          value: "mongodb://we-api-aks-mongo.we-api-prd.svc.cluster.local:27017/wedigitek"
        - name: WE_API_DB_NAME
          value: "wedigitek"
        - name: NODE_PATH
          value: "/wefood-delivery-notifier"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "200m"

