apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wefood-delivery-notifier-keyvault-env
  namespace: wefood-delivery-notifier-prd
spec:
  provider: azure
  secretObjects:
  - secretName: wefood-delivery-notifier-secrets-kv
    type: Opaque
    data:
    - objectName: all-env-secrets
      key: .env
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: ecc658e3-b1ba-46b7-8f7c-b5cf75272df2
    keyvaultName: kv-wedigitek-prd
    cloudName: ''
    objects: "array:\n  - |\n    objectName: wefood-delivery-notifier-all-env-secrets\n\
      \    objectType: secret\n    objectAlias: all-env-secrets"
    tenantId: 9fabb809-1920-4f77-8694-f9af659b5d21
