apiVersion: v1
kind: Service
metadata:
  name: wefood-delivery-notifier
  namespace: wefood-delivery-notifier-prd
  labels:
    app: wefood-delivery-notifier
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: wefood-delivery-notifier
