apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: devices-api-keyvault-env
  namespace: devices-api-prd
spec:
  provider: azure
  secretObjects:
  - secretName: devices-api-secrets-kv
    type: Opaque
    data:
    - objectName: devices-api-we-devices-api-we-api-host
      key: WE_DEVICES_API_WE_API_HOST
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: devices-api-we-devices-api-we-api-host
          objectType: secret
