apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notifications-service-prd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: notifications-service
  environment: production
  managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/notifications-service
    newTag: latest
