apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notifications-service-keyvault-env
  namespace: notifications-service-prd
spec:
  provider: azure
  secretObjects:
  - secretName: notifications-service-secrets-kv
    type: Opaque
    data:
    - objectName: notifications-service-logger
      key: LOGGER
    - objectName: notifications-service-loglevel
      key: LOGLEVEL
    - objectName: notifications-service-we-api-cdn-path
      key: WE_API_CDN_PATH
    - objectName: notifications-service-we-notification-services-api-db-connection-string
      key: WE_NOTIFICATION_SERVICES_API_DB_CONNECTION_STRING
    - objectName: notifications-service-we-notification-services-cdn-filesystem-path
      key: WE_NOTIFICATION_SERVICES_CDN_FILESYSTEM_PATH
    - objectName: notifications-service-we-notification-services-cdn-path
      key: WE_NOTIFICATION_SERVICES_CDN_PATH
    - objectName: notifications-service-we-notification-services-db-connection-string
      key: WE_NOTIFICATION_SERVICES_DB_CONNECTION_STRING
    - objectName: notifications-service-we-notification-services-mailersend-token
      key: WE_NOTIFICATION_SERVICES_MAILERSEND_TOKEN
    - objectName: notifications-service-we-notification-services-namespace
      key: WE_NOTIFICATION_SERVICES_NAMESPACE
    - objectName: notifications-service-we-notification-services-node-env
      key: WE_NOTIFICATION_SERVICES_NODE_ENV
    - objectName: notifications-service-we-notification-services-redis-url
      key: WE_NOTIFICATION_SERVICES_REDIS_URL
    - objectName: notifications-service-we-notification-services-slack-invoice-failures-webhook
      key: WE_NOTIFICATION_SERVICES_SLACK_INVOICE_FAILURES_WEBHOOK
    - objectName: notifications-service-we-notification-services-transporter
      key: WE_NOTIFICATION_SERVICES_TRANSPORTER
    - objectName: notifications-service-we-notifications-services-logger-enabled
      key: WE_NOTIFICATIONS_SERVICES_LOGGER_ENABLED
    - objectName: notifications-service-we-notifications-services-logger-lvl
      key: WE_NOTIFICATIONS_SERVICES_LOGGER_LVL
    - objectName: notifications-service-we-surveys-wefood-apis-base-url
      key: WE_SURVEYS_WEFOOD_APIS_BASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: notifications-service-logger
          objectType: secret
        - |
          objectName: notifications-service-loglevel
          objectType: secret
        - |
          objectName: notifications-service-we-api-cdn-path
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-api-db-connection-string
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-cdn-filesystem-path
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-cdn-path
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-db-connection-string
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-mailersend-token
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-namespace
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-node-env
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-redis-url
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-slack-invoice-failures-webhook
          objectType: secret
        - |
          objectName: notifications-service-we-notification-services-transporter
          objectType: secret
        - |
          objectName: notifications-service-we-notifications-services-logger-enabled
          objectType: secret
        - |
          objectName: notifications-service-we-notifications-services-logger-lvl
          objectType: secret
        - |
          objectName: notifications-service-we-surveys-wefood-apis-base-url
          objectType: secret
