apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reports-keyvault-env
  namespace: reports-prd
spec:
  provider: azure
  secretObjects:
  - secretName: reports-secrets-kv
    type: Opaque
    data:
    - objectName: reports-logger
      key: LOGGER
    - objectName: reports-loglevel
      key: LOGLEVEL
    - objectName: reports-we-data-api-services-db-connection-string
      key: WE_DATA_API_SERVICES_DB_CONNECTION_STRING
    - objectName: reports-we-reports-services-address
      key: WE_REPORTS_SERVICES_ADDRESS
    - objectName: reports-we-reports-services-logger-enabled
      key: WE_REPORTS_SERVICES_LOGGER_ENABLED
    - objectName: reports-we-reports-services-logger-lvl
      key: WE_REPORTS_SERVICES_LOGGER_LVL
    - objectName: reports-we-reports-services-namespace
      key: WE_REPORTS_SERVICES_NAMESPACE
    - objectName: reports-we-reports-services-node-env
      key: WE_REPORTS_SERVICES_NODE_ENV
    - objectName: reports-we-reports-services-port
      key: WE_REPORTS_SERVICES_PORT
    - objectName: reports-we-reports-services-transporter
      key: WE_REPORTS_SERVICES_TRANSPORTER
    - objectName: reports-we-reports-wefood-apis-base-url
      key: WE_REPORTS_WEFOOD_APIS_BASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: reports-logger
          objectType: secret
        - |
          objectName: reports-loglevel
          objectType: secret
        - |
          objectName: reports-we-data-api-services-db-connection-string
          objectType: secret
        - |
          objectName: reports-we-reports-services-address
          objectType: secret
        - |
          objectName: reports-we-reports-services-logger-enabled
          objectType: secret
        - |
          objectName: reports-we-reports-services-logger-lvl
          objectType: secret
        - |
          objectName: reports-we-reports-services-namespace
          objectType: secret
        - |
          objectName: reports-we-reports-services-node-env
          objectType: secret
        - |
          objectName: reports-we-reports-services-port
          objectType: secret
        - |
          objectName: reports-we-reports-services-transporter
          objectType: secret
        - |
          objectName: reports-we-reports-wefood-apis-base-url
          objectType: secret
