apiVersion: v1
kind: Secret
metadata:
  name: sefaz-services-secrets
  namespace: wedigitek-prd
type: Opaque
stringData:
  WE_SEFAZ_SERVICES_CERTS_PATH: /app/certificates/
  WE_SEFAZ_SERVICES_HOMOLOGACAO: "false"