apiVersion: apps/v1
kind: Deployment
metadata:
  name: we-docs
  namespace: we-docs-prd
  labels:
    app: we-docs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: we-docs
  template:
    metadata:
      labels:
        app: we-docs
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: we-docs
        image: ghcr.io/wedigitek/we-docs:rc
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - secretRef:
            name: we-docs-secrets-kv
        env:
        - name: PORT
          value: "80"
        - name: SERVER_PORT
          value: "80"
        volumeMounts:
        - name: keyvault-env
          mountPath: /mnt/secrets-store
          readOnly: true
        - name: we-docs-tokens
          mountPath: /we-docs/tokens/access.json
          subPath: access.json
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: keyvault-env
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: we-docs-keyvault-env
      - name: we-docs-tokens
        secret:
          secretName: we-docs-secrets-kv
