apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: we-docs-keyvault-env
  namespace: we-docs-prd
spec:
  provider: azure
  secretObjects:
  - secretName: we-docs-secrets-kv
    type: Opaque
    data:
    - objectName: we-docs-all-env-secrets
      key: .env
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: we-docs-all-env-secrets
          objectType: secret
