apiVersion: v1
kind: Service
metadata:
  name: we-docs
  namespace: we-docs-prd
  labels:
    app: we-docs
spec:
  selector:
    app: we-docs
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
