apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-runner
  namespace: wedigitek-prd
  labels:
    app: script-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script-runner
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "monitoring/nodejs-instrumentation"
      labels:
        app: script-runner
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: script-runner
        image: ghcr.io/wedigitek/script-runner:rc
        envFrom:
        - secretRef:
            name: script-runner-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "200m"
