apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: we-api-prd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - hpa.yaml
  - secretproviderclass-env.yaml
  - secretproviderclass-files.yaml

commonLabels:
  app: we-api
  environment: production
  managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/we-api
    newTag: latest
