apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: we-api-prd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - hpa.yaml
  - secretproviderclass-env.yaml
  - secretproviderclass-files.yaml

labels:
  - pairs:
      environment: production
      managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/we-api
    newName: ghcr.io/wedigitek/we-api
    newTag: rc
