apiVersion: v1
kind: Service
metadata:
  name: we-api-aks-mongo
  namespace: we-api-prd
  labels:
    app: we-api-aks-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: we-api-aks-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: we-api-aks-mongo
  namespace: we-api-prd
  labels:
    app: we-api-aks-mongo
spec:
  serviceName: we-api-aks-mongo
  replicas: 1
  selector:
    matchLabels:
      app: we-api-aks-mongo
  template:
    metadata:
      labels:
        app: we-api-aks-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          args:
            - --bind_ip_all
            - --wiredTigerCacheSizeGB
            - "1"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 150Gi
        storageClassName: managed-csi