apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: we-api-keyvault-files
  namespace: we-api-prd
spec:
  provider: azure
  secretObjects:
  - secretName: we-api-files-kv
    type: Opaque
    data:
    - objectName: jwtRS256.key
      key: jwtRS256.key
    - objectName: jwtRS256.key.pub
      key: jwtRS256.key.pub
    - objectName: menugrsa.json
      key: menugrsa.json
    - objectName: deli-2f288.json
      key: deli-2f288.json
    - objectName: sodexo-54882.json
      key: sodexo-54882.json
    - objectName: ticket-public-cert.cer
      key: ticket-public-cert.cer
    - objectName: api-keys.json
      key: api-keys.json
    - objectName: AuthKey_9984Z5GVCJ.p8
      key: AuthKey_9984Z5GVCJ.p8
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: ecc658e3-b1ba-46b7-8f7c-b5cf75272df2
    keyvaultName: kv-wedigitek-prd
    cloudName: ''
    objects: "array:\n  - |\n    objectName: we-api-jwt-rs256-key\n    objectType:\
      \ secret\n    objectAlias: jwtRS256.key\n  - |\n    objectName: we-api-jwt-rs256-key-pub\n\
      \    objectType: secret\n    objectAlias: jwtRS256.key.pub\n  - |\n    objectName:\
      \ we-api-firebase-menugrsa-json\n    objectType: secret\n    objectAlias: menugrsa.json\n\
      \  - |\n    objectName: we-api-firebase-deli-2f288-json\n    objectType: secret\n\
      \    objectAlias: deli-2f288.json\n  - |\n    objectName: we-api-firebase-sodexo-54882-json\n\
      \    objectType: secret\n    objectAlias: sodexo-54882.json\n  - |\n    objectName:\
      \ we-api-ticket-public-cert\n    objectType: secret\n    objectAlias: ticket-public-cert.cer\n\
      \  - |\n    objectName: we-api-api-keys-json\n    objectType: secret\n    objectAlias:\
      \ api-keys.json\n  - |\n    objectName: we-api-socialauth-apple-key-p8\n   \
      \ objectType: secret\n    objectAlias: AuthKey_9984Z5GVCJ.p8\n"
    tenantId: 9fabb809-1920-4f77-8694-f9af659b5d21
