apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: we-api-keyvault-files
  namespace: we-api-prd
spec:
  provider: azure
  secretObjects:
  - secretName: we-api-files-kv
    type: Opaque
    data:
    - objectName: jwtRS256.key
      key: jwtRS256.key
    - objectName: jwtRS256.key.pub
      key: jwtRS256.key.pub
    - objectName: firebase-menugrsa.json
      key: firebase-menugrsa.json
    - objectName: firebase-deli-2f288.json
      key: firebase-deli-2f288.json
    - objectName: firebase-sodexo-54882.json
      key: firebase-sodexo-54882.json
    - objectName: ticket-public-cert.cer
      key: ticket-public-cert.cer
    - objectName: api-keys.json
      key: api-keys.json
    - objectName: AuthKey_9984Z5GVCJ.p8
      key: AuthKey_9984Z5GVCJ.p8
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: we-api-jwt-rs256-key
          objectType: secret
          objectAlias: jwtRS256.key
        - |
          objectName: we-api-jwt-rs256-key-pub
          objectType: secret
          objectAlias: jwtRS256.key.pub
        - |
          objectName: we-api-firebase-menugrsa-json
          objectType: secret
          objectAlias: firebase-menugrsa.json
        - |
          objectName: we-api-firebase-deli-2f288-json
          objectType: secret
          objectAlias: firebase-deli-2f288.json
        - |
          objectName: we-api-firebase-sodexo-54882-json
          objectType: secret
          objectAlias: firebase-sodexo-54882.json
        - |
          objectName: we-api-ticket-public-cert
          objectType: secret
          objectAlias: ticket-public-cert.cer
        - |
          objectName: we-api-api-keys-json
          objectType: secret
          objectAlias: api-keys.json
        - |
          objectName: we-api-socialauth-apple-key-p8
          objectType: secret
          objectAlias: AuthKey_9984Z5GVCJ.p8
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
