apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payments-keyvault-env
  namespace: payments-prd
spec:
  provider: azure
  secretObjects:
  - secretName: payments-secrets-kv
    type: Opaque
    data:
    - objectName: payments-logger
      key: LOGGER
    - objectName: payments-loglevel
      key: LOGLEVEL
    - objectName: payments-servicedir
      key: SERVICEDIR
    - objectName: payments-we-payment-services-db-connection-string
      key: WE_PAYMENT_SERVICES_DB_CONNECTION_STRING
    - objectName: payments-we-payment-services-namespace
      key: WE_PAYMENT_SERVICES_NAMESPACE
    - objectName: payments-we-payment-services-node-env
      key: WE_PAYMENT_SERVICES_NODE_ENV
    - objectName: payments-we-payment-services-transporter
      key: WE_PAYMENT_SERVICES_TRANSPORTER
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: payments-logger
          objectType: secret
        - |
          objectName: payments-loglevel
          objectType: secret
        - |
          objectName: payments-servicedir
          objectType: secret
        - |
          objectName: payments-we-payment-services-db-connection-string
          objectType: secret
        - |
          objectName: payments-we-payment-services-namespace
          objectType: secret
        - |
          objectName: payments-we-payment-services-node-env
          objectType: secret
        - |
          objectName: payments-we-payment-services-transporter
          objectType: secret
