apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: quality-control-keyvault-env
  namespace: quality-control-prd
spec:
  provider: azure
  secretObjects:
  - secretName: quality-control-secrets-kv
    type: Opaque
    data:
    - objectName: quality-control-logger
      key: LOGGER
    - objectName: quality-control-loglevel
      key: LOGLEVEL
    - objectName: quality-control-servicedir
      key: SERVICEDIR
    - objectName: quality-control-we-qa-services-db-connection-string
      key: WE_QA_SERVICES_DB_CONNECTION_STRING
    - objectName: quality-control-we-qa-services-namespace
      key: WE_QA_SERVICES_NAMESPACE
    - objectName: quality-control-we-qa-services-node-env
      key: WE_QA_SERVICES_NODE_ENV
    - objectName: quality-control-we-qa-services-no-reply-email
      key: WE_QA_SERVICES_NO_REPLY_EMAIL
    - objectName: quality-control-we-qa-services-no-reply-password
      key: WE_QA_SERVICES_NO_REPLY_PASSWORD
    - objectName: quality-control-we-qa-services-transporter
      key: WE_QA_SERVICES_TRANSPORTER
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: quality-control-logger
          objectType: secret
        - |
          objectName: quality-control-loglevel
          objectType: secret
        - |
          objectName: quality-control-servicedir
          objectType: secret
        - |
          objectName: quality-control-we-qa-services-db-connection-string
          objectType: secret
        - |
          objectName: quality-control-we-qa-services-namespace
          objectType: secret
        - |
          objectName: quality-control-we-qa-services-node-env
          objectType: secret
        - |
          objectName: quality-control-we-qa-services-no-reply-email
          objectType: secret
        - |
          objectName: quality-control-we-qa-services-no-reply-password
          objectType: secret
        - |
          objectName: quality-control-we-qa-services-transporter
          objectType: secret
