apiVersion: apps/v1
kind: Deployment
metadata:
  name: we-menu
  namespace: wedigitek-prd
  labels:
    app: we-menu
spec:
  replicas: 0
  selector:
    matchLabels:
      app: we-menu
  template:
    metadata:
      labels:
        app: we-menu
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: we-menu
        image: ghcr.io/wedigitek/we-menu:rc
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "200m"
