apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wefood-realtime-server-prd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: wefood-realtime-server
  environment: production
  managed-by: argocd

images:
  - name: acrwedigitekprd.azurecr.io/wefood-realtime-server
    newTag: latest
