apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wefood-realtime-server-keyvault-env
  namespace: wefood-realtime-server-prd
spec:
  provider: azure
  secretObjects:
  - secretName: wefood-realtime-server-secrets-kv
    type: Opaque
    data:
    - objectName: wefood-realtime-server-node-env
      key: NODE_ENV
    - objectName: wefood-realtime-server-node-path
      key: NODE_PATH
    - objectName: wefood-realtime-server-wefood-rt-server-logger-enabled
      key: WEFOOD_RT_SERVER_LOGGER_ENABLED
    - objectName: wefood-realtime-server-wefood-rt-server-logger-lvl
      key: WEFOOD_RT_SERVER_LOGGER_LVL
    - objectName: wefood-realtime-server-wefood-rt-server-we-api-auth-token
      key: WEFOOD_RT_SERVER_WE_API_AUTH_TOKEN
    - objectName: wefood-realtime-server-wefood-rt-server-we-api-base-url
      key: WEFOOD_RT_SERVER_WE_API_BASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: wefood-realtime-server-node-env
          objectType: secret
        - |
          objectName: wefood-realtime-server-node-path
          objectType: secret
        - |
          objectName: wefood-realtime-server-wefood-rt-server-logger-enabled
          objectType: secret
        - |
          objectName: wefood-realtime-server-wefood-rt-server-logger-lvl
          objectType: secret
        - |
          objectName: wefood-realtime-server-wefood-rt-server-we-api-auth-token
          objectType: secret
        - |
          objectName: wefood-realtime-server-wefood-rt-server-we-api-base-url
          objectType: secret
