apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: data-api-keyvault-env
  namespace: data-api-prd
spec:
  provider: azure
  secretObjects:
  - secretName: data-api-secrets-kv
    type: Opaque
    data:
    - objectName: data-api-we-api-export-days-logs-limit
      key: WE_API_EXPORT_DAYS_LOGS_LIMIT
    - objectName: data-api-we-dataapi-db--connection-string
      key: WE_DATAAPI_DB__CONNECTION_STRING
    - objectName: data-api-we-data-api-services-address
      key: WE_DATA_API_SERVICES_ADDRESS
    - objectName: data-api-we-data-api-services-billing-db-connection-string
      key: WE_DATA_API_SERVICES_BILLING_DB_CONNECTION_STRING
    - objectName: data-api-we-data-api-services-db-connection-string
      key: WE_DATA_API_SERVICES_DB_CONNECTION_STRING
    - objectName: data-api-we-data-api-swagger-password
      key: WE_DATA_API_SWAGGER_PASSWORD
    - objectName: data-api-we-data-api-swagger-username
      key: WE_DATA_API_SWAGGER_USERNAME
    - objectName: data-api-we-log-connection-string
      key: WE_LOG_CONNECTION_STRING
    - objectName: data-api-we-notification-services-db-connection-string
      key: WE_NOTIFICATION_SERVICES_DB_CONNECTION_STRING
    - objectName: data-api-we-surveys-wefood-apis-base-url
      key: WE_SURVEYS_WEFOOD_APIS_BASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecc658e3-b1ba-46b7-8f7c-b5cf75272df2"
    keyvaultName: "kv-wedigitek-prd"
    tenantId: "9fabb809-1920-4f77-8694-f9af659b5d21"
    objects: |
      array:
        - |
          objectName: data-api-we-api-export-days-logs-limit
          objectType: secret
        - |
          objectName: data-api-we-dataapi-db--connection-string
          objectType: secret
        - |
          objectName: data-api-we-data-api-services-address
          objectType: secret
        - |
          objectName: data-api-we-data-api-services-billing-db-connection-string
          objectType: secret
        - |
          objectName: data-api-we-data-api-services-db-connection-string
          objectType: secret
        - |
          objectName: data-api-we-data-api-swagger-password
          objectType: secret
        - |
          objectName: data-api-we-data-api-swagger-username
          objectType: secret
        - |
          objectName: data-api-we-log-connection-string
          objectType: secret
        - |
          objectName: data-api-we-notification-services-db-connection-string
          objectType: secret
        - |
          objectName: data-api-we-surveys-wefood-apis-base-url
          objectType: secret
